### ISSUE TITLE
ACTIVIDAD 10

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-4as_coders#1]
[ACTIVIDAD 10.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-4as_coders/files/15478891/ACTIVIDAD.10.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
